### ISSUE TITLE
work2 ch2 的進位位數問題

### ISSUE THREAD

**Issue by Lauviah0622** [Lidemy/mentor-program-4th-WooooHuan#6]
@WooooHuan 同學你好🖐🖐🖐
在作業參考上看到你的作業，後來發現寫得非常之精簡
自己就拿來參考看看為什麼一樣的題目自己會寫到百行...
然後在 ch2 發現一點小問題：如果輸入 25 * 25 => 525

後來仔細看一下應該是因為這個部分，進位位數沒有加上原位數導致小錯誤

https://github.com/Lidemy/mentor-program-4th-WooooHuan/blob/0b8dc54343ede34edc8e0e7769a38499171daa0d/homeworks/week2/ch3.js#L13

偶然發現想說提醒一下。挑戰題真的寫的很好，然後 code 也看起來很簡潔！謝謝你～

**Comment by WooooHuan** [comment]
@Lauviah0622 哦！我還真的沒發現哈哈哈哈。
感謝指正，目前已將內容修正到 `master` 分支上了～
另外，我一開始也都是先寫一大串，最後才開始進行收斂的，被這樣說有點不好意思 😬
如果有什麼需要的話，可以直接敲我 slack, 有看到就會回，但我不見得答得上來就是 😋
四期生 GOGO～
